---
AWSTemplateFormatVersion: "2010-09-09"
Description: Example cloud formation template
Parameters:
  Name:
    Description: Name of the stack
    Type: String
  Domain:
    Description: Domain or application for which this stack is
    Type: String
  Version:
    Description: Version of the template
    Type: String
  BucketName:
    Description: Bucket where the templates will live
    Type: String
  VPCCIDR:
    Description: CIDR block for the VPC
    Type: String
Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VPCCIDR
      InstanceTenancy: default
      EnableDnsSupport: "true"
      EnableDnsHostnames: "true"
      Tags:
        - Key: Name
          Value: !Ref AWS::StackName
Outputs:
  VPCID:
    Value: !Ref VPC
    Description: VPC ID
    Export:
      Name: !Sub "${AWS::StackName}-VPCID"
